'use strict';
const {chromium,expect}=require('@playwright/test');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawn}=require('node:child_process');
(async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'dss-app-browser-')),shots=path.resolve('.private/qa-applications');fs.mkdirSync(shots,{recursive:true});
 const server=spawn(process.execPath,['backend.js'],{cwd:path.resolve(__dirname,'..'),env:{...process.env,DATABASE_URL:'',WORKOS_API_KEY:'',WORKOS_CLIENT_ID:'',ADMIN_USERNAME:'',ADMIN_PASSWORD_HASH:'',VERCEL:'',NODE_ENV:'test',DSS_MANUAL_SETUP:'0',DSS_DATA_DIR:dir,PORT:'0'},windowsHide:true,stdio:['ignore','pipe','pipe']});let browser;
 try{
  const base=await new Promise((resolve,reject)=>{let out='';server.stdout.on('data',chunk=>{out+=chunk;const match=/DSS website: (http:\/\/localhost:\d+)/.exec(out);if(match)resolve(match[1]);});server.on('error',reject);});
  browser=await chromium.launch({channel:'chrome',headless:true});const errors=[],latencies=[];console.log('Browser verification started');
  async function context(){const context=await browser.newContext({viewport:{width:1440,height:1000}});context.setDefaultTimeout(15000);return context;}
  async function page(context){const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));return page;}
  const ac=await context(),nc=await context(),gc=await context(),admin=await page(ac),normal=await page(nc),visitor=await page(gc),login=await page(gc);
  assert.equal((await ac.request.post(base+'/api/auth/login',{data:{username:'admin',password:'pass'}})).status(),200);
  assert.equal((await nc.request.post(base+'/api/auth/register',{data:{name:'Test Learner',email:'learner@example.test',password:'Test-password-123'}})).status(),201);
  await admin.goto(base+'/admin');await admin.getByRole('heading',{name:'Your society, at a glance.'}).waitFor();
  await normal.goto(base+'/member-dashboard.html');await expect(normal.locator('body')).toHaveAttribute('data-workspace-role','student');assert.ok(!(await normal.locator('body').innerText()).toLowerCase().includes('cabinet'));
  assert.equal(await normal.getByRole('link',{name:'Apply for membership',exact:true}).count(),0);
  await visitor.goto(base+'/index.html');await visitor.waitForFunction(()=>window.DSS?.content);await expect(visitor.locator('a[href="ambassador.html"]').first()).toBeHidden();
  await login.goto(base+'/login.html');await expect(login.locator('.auth-card h2')).toBeVisible();
  console.log('Checking application controls');await admin.getByRole('button',{name:'Applications & questions',exact:true}).click();
  let t=Date.now();await admin.locator('[data-application-toggle=membership]').check();await expect(normal.getByRole('link',{name:'Apply for membership',exact:true}).first()).toBeVisible();latencies.push({change:'open membership',ms:Date.now()-t});
  await expect(visitor.locator('a[href="opportunities.html"]').first()).toBeVisible();
  await admin.locator('[data-application-toggle=ambassador]').check();await expect(normal.getByRole('link',{name:'Apply for ambassador',exact:true})).toBeVisible();
  // Add both question types through the actual admin UI.
  for(const [type,question,answerType]of [['membership','Can you attend weekly?','yesno'],['ambassador','What would help your campus?','textarea']]){
   await admin.locator('[data-action=add-question][data-type='+type+']').click();await admin.getByLabel('Question',{exact:true}).fill(question);await admin.getByLabel('Answer type',{exact:true}).selectOption(answerType);await admin.getByRole('button',{name:'Save question',exact:true}).click();await admin.locator('#editor-dialog').waitFor({state:'hidden'});
  }
  await normal.goto(base+'/join.html?track=membership');await normal.getByLabel('University / institution *',{exact:true}).fill('Test University');await normal.getByLabel('Your interests *',{exact:true}).fill('Data science');await normal.getByLabel('How would you like to contribute? *',{exact:true}).fill('I will build useful notebooks and share resources with the society.');await normal.getByLabel('Can you attend weekly? *',{exact:true}).selectOption('no');
  // Editing questions must update open forms without losing typed answers.
  await admin.locator('[data-action=edit-question][data-type=membership][data-index="0"]').click();await admin.getByLabel('Question',{exact:true}).fill('Your institution');await admin.getByRole('button',{name:'Save question',exact:true}).click();await admin.locator('#editor-dialog').waitFor({state:'hidden'});
  await expect(normal.getByLabel('Your institution *',{exact:true})).toHaveValue('Test University');await expect(normal.getByLabel('Can you attend weekly? *',{exact:true})).toHaveValue('no');
  await normal.getByRole('button',{name:'Submit application',exact:true}).click();await normal.waitForURL('**/member-dashboard.html');await expect(normal.locator('#member-content')).toContainText('Membership application: pending');await expect(normal.locator('body')).toHaveAttribute('data-workspace-role','student');
  await admin.getByRole('button',{name:'Members & approvals',exact:true}).click();await admin.getByRole('button',{name:'Refresh',exact:true}).click();await admin.getByRole('button',{name:'Review application',exact:true}).click();await expect(admin.locator('#editor-dialog')).toContainText('Can you attend weekly?: No');await admin.getByLabel('Membership application decision',{exact:true}).selectOption('approved');await admin.getByRole('button',{name:'Save account review',exact:true}).click();await admin.locator('#editor-dialog').waitFor({state:'hidden'});await expect(normal.locator('body')).toHaveAttribute('data-workspace-role','member');await expect(normal.locator('[data-member-tab=contributions]')).toBeVisible();
  await normal.goto(base+'/ambassador.html');await normal.getByLabel('University / institution *',{exact:true}).fill('Test University');
  for(const [name,value]of [['University student ID','BS-101'],['Degree programme','Data Science'],['Mobile / WhatsApp number','03001234567'],['Campus city','Lahore'],['Province / region','Punjab'],['Current semester','4'],['CNIC / B-form number','12345-1234567-1'],['Weekly commitment','2–3 hours'],['What would you organise in your first month?','A practical workshop on Python notebooks and open data.'],['What would help your campus?','More practical workshops with shared resources.']])await normal.getByLabel(name+' *',{exact:true}).fill(value);
  await normal.getByLabel('I confirm these details are accurate and consent to application review. *',{exact:true}).selectOption('yes');await normal.getByRole('button',{name:'Submit application',exact:true}).click();await normal.waitForURL('**/member-dashboard.html');await expect(normal.locator('body')).toHaveAttribute('data-workspace-role','member');
  await admin.getByRole('button',{name:'Refresh',exact:true}).click();await admin.getByRole('button',{name:'Review application',exact:true}).click();await admin.getByLabel('Ambassador application decision',{exact:true}).selectOption('approved');await admin.getByRole('button',{name:'Save account review',exact:true}).click();await admin.locator('#editor-dialog').waitFor({state:'hidden'});await expect(normal.locator('body')).toHaveAttribute('data-workspace-role','ambassador');await expect(normal.getByRole('button',{name:'Submit activity report',exact:true})).toBeVisible();
  // A closed page disappears immediately, including one that was already open.
  const openForm=await page(nc);await openForm.goto(base+'/ambassador.html');await openForm.waitForFunction(()=>window.DSS?.content);
  await admin.getByRole('button',{name:'Applications & questions',exact:true}).click();t=Date.now();await admin.locator('[data-application-toggle=ambassador]').uncheck();await expect(openForm.locator('main')).toBeHidden();latencies.push({change:'close ambassador',ms:Date.now()-t});await expect(visitor.locator('a[href="ambassador.html"]').first()).toBeHidden();assert.equal((await gc.request.get(base+'/ambassador.html')).status(),404);
  await admin.locator('[data-application-toggle=ambassador]').check();await expect(openForm.locator('main')).toBeVisible();
  await admin.getByRole('button',{name:'Role workspaces',exact:true}).click();t=Date.now();await admin.locator('[name=ambassadorHeading]').fill('Lead your campus with purpose.');await admin.locator('[name=ambassadorHeading]').blur();await expect(normal.getByRole('heading',{name:'Lead your campus with purpose.'})).toBeVisible();latencies.push({change:'edit portal heading',ms:Date.now()-t});
  assert.equal(await admin.locator('#workspace-settings .panel').count(),8);
  // Preview all three user pages and login, then publish an element edit.
  await admin.getByRole('button',{name:'Page editor',exact:true}).click();
  for(const [name,role]of [['student-dashboard','student'],['member-dashboard','member'],['ambassador-dashboard','ambassador']]){await admin.locator('#page-select').selectOption(name);await expect(admin.frameLocator('#page-preview').locator('body')).toHaveAttribute('data-workspace-role',role);assert.ok(!(await admin.frameLocator('#page-preview').locator('body').innerText()).toLowerCase().includes('cabinet'));}
  const frame=admin.frameLocator('#page-preview');await frame.locator('.workspace-welcome h2').click();await admin.getByLabel('Text content',{exact:true}).fill('Your campus, your community.');await admin.getByRole('button',{name:'Apply to preview',exact:true}).click();await expect(normal.getByRole('heading',{name:'Your campus, your community.'})).toBeVisible();
  await admin.locator('#page-select').selectOption('login');await frame.locator('.auth-card h2').waitFor();await frame.locator('.auth-card h2').click();await admin.getByLabel('Text content',{exact:true}).fill('Welcome to your community.');await admin.getByRole('button',{name:'Apply to preview',exact:true}).click();await expect(login.getByRole('heading',{name:'Welcome to your community.'})).toBeVisible();
  for(const width of [320,768,1440]){await normal.setViewportSize({width,height:900});assert.ok(await normal.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Portal overflow '+width);}
  await normal.screenshot({path:path.join(shots,'ambassador-mobile.png'),fullPage:true});await admin.screenshot({path:path.join(shots,'portal-editor.png')});
  assert.deepEqual(errors,[]);console.log(JSON.stringify({threePortals:true,questionEditing:true,approvals:true,closedPages:true,portalPageEditor:true,mobileLayouts:true,latencies,screenshots:shots}));
 }catch(error){if(browser)for(const [i,context]of browser.contexts().entries())await context.pages()[0]?.screenshot({path:path.join(shots,'failure-'+i+'.png'),fullPage:true}).catch(()=>{});throw error;}
 finally{await browser?.close();if(server.exitCode===null){const exited=new Promise(r=>server.once('exit',r));server.kill();await exited;}fs.rmSync(dir,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
