const {chromium,expect}=require('@playwright/test');
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process');
(async()=>{
const data=fs.mkdtempSync(path.join(os.tmpdir(),'dss-members-v4-')),shots=path.resolve('.private/qa-v4');fs.mkdirSync(shots,{recursive:true});
const server=spawn(process.execPath,['server.js'],{env:{...process.env,DSS_MANUAL_SETUP:'0',PORT:'0',DSS_DATA_DIR:data},windowsHide:true,stdio:['ignore','pipe','pipe']});let browser;
try{
const base=await new Promise((resolve,reject)=>{let out='';server.stdout.on('data',d=>{out+=d;const m=/DSS website: (http:\/\/localhost:\d+)/.exec(out);if(m)resolve(m[1]);});server.once('error',reject);});
browser=await chromium.launch({channel:'chrome',headless:true});const ac=await browser.newContext({viewport:{width:1440,height:1000}}),sc=await browser.newContext({viewport:{width:1440,height:1000}}),gc=await browser.newContext();for(const c of [ac,sc,gc])c.setDefaultTimeout(15000);const admin=await ac.newPage(),student=await sc.newPage(),errors=[];for(const p of [admin,student])p.on('pageerror',e=>errors.push(e.message));
await ac.request.post(base+'/api/auth/login',{data:{email:'admin',password:'pass'}});
await sc.request.post(base+'/api/auth/register',{data:{name:'Hira Ahmed',email:'hira@example.test',password:'Member-password-123'}});
await student.goto(base+'/member-dashboard.html');await student.getByRole('heading',{name:'What will you learn today?'}).waitFor();assert.equal(await student.locator('[data-member-tab=contributions]').count(),0);await student.screenshot({path:path.join(shots,'student-desktop.png')});
assert.equal((await sc.request.post(base+'/api/member/contribution',{data:{title:'Forbidden',description:'A student cannot submit society work.'}})).status(),403);
await student.goto(base+'/join.html?track=membership');await expect(student.locator('#account-fields')).toBeHidden();await student.locator('#applicant-university').fill('University in Lahore');await student.locator('#applicant-interest').fill('Data visualisation');await student.locator('#applicant-motivation').fill('I would like to contribute accessible learning resources and notebooks.');await student.getByRole('button',{name:'Submit application',exact:true}).click();await student.waitForURL('**/member-dashboard.html');await expect(student.locator('.note')).toContainText('Membership application: pending');
let me=await(await sc.request.get(base+'/api/auth/me')).json();assert.equal(me.user.role,'student');assert.equal(me.user.status,'approved');
assert.equal((await sc.request.post(base+'/api/member/membership-application',{data:{}})).status(),409);
await admin.goto(base+'/admin.html');await admin.getByRole('button',{name:'Members & approvals',exact:true}).click();await admin.getByRole('button',{name:'Review application'}).click();await admin.getByLabel('Membership application decision',{exact:true}).selectOption('approved');await admin.getByRole('button',{name:'Save account review'}).click();await admin.locator('#editor-dialog').waitFor({state:'hidden'});
// The already open student dashboard receives the role change over the event stream.
await expect(student.getByRole('heading',{name:'Make your next contribution.'})).toBeVisible();await expect(student.locator('body')).toHaveAttribute('data-member-role','member');
await admin.getByRole('button',{name:'Content library',exact:true}).click();await admin.locator('#collection').selectOption('opportunities');await admin.getByRole('button',{name:'Add record',exact:true}).click();await admin.getByLabel('Title',{exact:true}).fill('Pakistan open-data notebook');await admin.getByLabel('Desc',{exact:true}).fill('Help the society build a useful data notebook.');await admin.getByRole('button',{name:'Apply changes',exact:true}).click();await admin.locator('#editor-dialog').waitFor({state:'hidden'});await expect(student.getByRole('heading',{name:'Pakistan open-data notebook'})).toBeVisible();
assert.equal((await(await gc.request.get(base+'/api/content')).json()).collections.opportunities.length,0);
await student.getByRole('button',{name:'Submit contribution',exact:true}).click();await student.getByLabel('Title',{exact:true}).fill('My first analysis');await student.getByLabel('Description',{exact:true}).fill('A reproducible notebook exploring an openly available dataset.');await student.getByRole('button',{name:'Submit for review'}).click();await student.locator('#editor-dialog').waitFor({state:'hidden'});
await admin.getByRole('button',{name:'Contributions',exact:true}).click();await admin.getByRole('button',{name:'Refresh',exact:true}).click();await admin.getByRole('button',{name:'Review contribution'}).click();await admin.getByLabel('Status',{exact:true}).selectOption('approved');await admin.getByLabel('Review Note',{exact:true}).fill('Clear and reproducible work. Thank you.');await admin.getByRole('button',{name:'Save review'}).click();await admin.locator('#editor-dialog').waitFor({state:'hidden'});await expect(student.locator('#member-content')).toContainText('Clear and reproducible work. Thank you.');
await student.screenshot({path:path.join(shots,'member-desktop.png')});
for(const tab of ['library','events','saved','contributions']){await student.locator('[data-member-tab='+tab+']').click();assert.ok(await student.locator('#member-content').innerText());}
await student.setViewportSize({width:320,height:844});assert.ok(await student.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await student.screenshot({path:path.join(shots,'member-mobile.png'),fullPage:true});
await student.goto(base+'/index.html');await student.emulateMedia({reducedMotion:'reduce'});await expect(student.locator('.surface-stage')).toHaveAttribute('data-running','false');await student.locator('[data-pattern=clusters]').click();await expect(student.locator('[data-pattern=clusters]')).toHaveAttribute('aria-pressed','true');assert.ok(await student.evaluate(()=>document.fonts.check('16px Inter')));
assert.deepEqual(errors,[]);console.log('Member v4 checks passed: student upgrade, separate member workspace, live role/content/review updates, opportunity privacy, contribution approval, tabs, mobile layout and reduced motion.');
}finally{await browser?.close();if(server.exitCode===null){const exited=new Promise(r=>server.once('exit',r));server.kill();await exited;}}
})().catch(e=>{console.error(e);process.exitCode=1;});
