import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'bannerSettings',
  title: 'Announcement Banner & Alerts',
  type: 'document',
  fields: [
    defineField({
      name: 'bannerActive',
      title: 'Enable Announcement Banner',
      type: 'boolean',
      initialValue: true,
      description: 'Toggle on to display this banner across website pages.',
    }),
    defineField({
      name: 'shape',
      title: 'Banner Shape & Format',
      type: 'string',
      initialValue: 'box-card',
      options: {
        list: [
          { title: '📦 Box Shape (Rich Card with Title, Subtext & Action Buttons)', value: 'box-card' },
          { title: '💊 Capsule / Pill Shape (Sleek Compact Single-Line Bar)', value: 'pill-capsule' },
          { title: '〰️ Line Streamer (Flowing Particle Marquee Line)', value: 'line-streamer' },
          { title: '📌 Full-Width Header/Footer Bar (Pinned Edge-to-Edge)', value: 'bar-header' },
          { title: '📐 Corner Ribbon Badge (Diagonal Origami Edge)', value: 'corner-ribbon' },
        ],
      },
      description: 'Choose the visual shape and structure for the banner.',
    }),
    defineField({
      name: 'position',
      title: 'Placement & Screen Anchor',
      type: 'string',
      initialValue: 'bottom-left',
      options: {
        list: [
          { title: '↙️ Bottom Left (Floating)', value: 'bottom-left' },
          { title: '↘️ Bottom Right (Floating)', value: 'bottom-right' },
          { title: '↖️ Top Left (Floating below header)', value: 'top-left' },
          { title: '↗️ Top Right (Floating below header)', value: 'top-right' },
          { title: '⬇️ Bottom Center (Floating center dock)', value: 'bottom-center' },
          { title: '⬆️ Top Center (Floating top dock)', value: 'top-center' },
          { title: '🔝 Top Bar (Pinned to very top of page)', value: 'top-bar' },
          { title: '🔚 Bottom Bar (Pinned to very bottom of page)', value: 'bottom-bar' },
        ],
      },
      description: 'Select where on the screen the banner should be placed.',
    }),
    defineField({
      name: 'animation',
      title: 'Animation & Flow Dynamics',
      type: 'string',
      initialValue: 'float-pulse',
      options: {
        list: [
          { title: '✨ Floating Hover with Pulsing Glow (Glides gently)', value: 'float-pulse' },
          { title: '🌊 Flowing Streamer Right-to-Left (Continuous particle flow)', value: 'flow-rtl' },
          { title: '🏄 Flowing Streamer Left-to-Right (Continuous particle flow)', value: 'flow-ltr' },
          { title: '🚀 Smooth Slide-In from Screen Edge', value: 'slide-in' },
          { title: '🎯 Subtle Periodic Attention Bounce', value: 'bounce-subtle' },
          { title: '🧊 Static Frosted Glass (No motion)', value: 'static-glass' },
        ],
      },
      description: 'Control how the banner moves or flows across the website.',
    }),
    defineField({
      name: 'badgeText',
      title: 'Badge / Tag Text',
      type: 'string',
      initialValue: '⚡ HACKATHON',
      description: 'Short highlighted badge tag (e.g. ⚡ HACKATHON, 🚀 FELLOWSHIP, 🔥 NEW PREPRINT).',
    }),
    defineField({
      name: 'bannerText',
      title: 'Main Headline / Title',
      type: 'string',
      initialValue: 'Fall 2026 AI Hackathon Registration Open',
      description: 'Main notification title displayed to visitors.',
    }),
    defineField({
      name: 'subText',
      title: 'Secondary Subtext / Description',
      type: 'string',
      initialValue: 'Join 500+ researchers and build frontier multi-agent AI systems.',
      description: 'Additional description (shown prominently in Box shape).',
    }),
    defineField({
      name: 'targetPage',
      title: 'Target Page Destination',
      type: 'string',
      initialValue: 'events.html',
      options: {
        list: [
          { title: '🎯 Events & Hackathons (events.html)', value: 'events.html' },
          { title: '🚀 Membership & Fellowships (join.html)', value: 'join.html' },
          { title: '🔐 Member Portal Login (login.html)', value: 'login.html' },
          { title: '📄 Academic Research & Preprints (research.html)', value: 'research.html' },
          { title: '💻 Code Repositories & Projects (projects.html)', value: 'projects.html' },
          { title: '📰 Society Blog & News (blog.html)', value: 'blog.html' },
          { title: '📚 Learning Resources (resources.html)', value: 'resources.html' },
          { title: '🌐 About Us (about.html)', value: 'about.html' },
          { title: '✉️ Contact Us (contact.html)', value: 'contact.html' },
          { title: '🔗 Custom External Link', value: 'custom' },
        ],
      },
      description: 'Choose which page the user should navigate to when clicking the banner.',
    }),
    defineField({
      name: 'customUrl',
      title: 'Custom External URL (if Custom is chosen)',
      type: 'url',
      description: 'Enter a custom link (e.g. https://github.com/... or https://discord.gg/...) if not linking to an internal page.',
    }),
    defineField({
      name: 'ctaText',
      title: 'Call-To-Action Button Label',
      type: 'string',
      initialValue: 'Click to Register →',
      description: 'Button text (e.g. "Register Now →", "Explore Page →", "Apply Here →").',
    }),
    defineField({
      name: 'colorGradient',
      title: 'Color Accent & Glow Theme',
      type: 'string',
      initialValue: 'sky-indigo',
      options: {
        list: [
          { title: 'Electric Sky & Deep Indigo (Default)', value: 'sky-indigo' },
          { title: 'Cyber Emerald & Neon Teal', value: 'emerald-teal' },
          { title: 'Solar Amber & Flame Rose', value: 'amber-rose' },
          { title: 'Violet Amethyst & Cyan Pulse', value: 'purple-cyan' },
          { title: 'Monochrome Gold & Obsidian', value: 'monochrome-gold' },
        ],
      },
      description: 'Choose the visual color theme for the banner glow and buttons.',
    }),
  ],
})

